# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    branches: [main]
    tags: "v*.*.*"  # A tag push is not associated with a branch, so OR with this.
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set up Python.
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install any requirements
      run: |
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

    - name: Run tests including doctest
      run: |
        python -m pip install pytest
        pytest --doctest-modules

    - name: Run mypy
      if: false  # mypy is slow (5 minutes) and has problems with numpy.
      run: |
        python -m pip install mypy
        # Omit "--strict" because numpy on github has type stubs.
        mypy --exclude 'build/|setup.py' .

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pip install build --user
        python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
